<?php

namespace App\Filament\Resources\Projects\Tables;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Actions\ViewAction;
use Filament\Tables\Columns\IconColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

class ProjectsTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('legacy_project_id')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('organization.name')
                    ->searchable(),
                TextColumn::make('title')
                    ->searchable(),
                TextColumn::make('stage')
                    ->searchable(),
                TextColumn::make('estate')
                    ->searchable(),
                TextColumn::make('total_lots')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('storeys')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('min_landsize')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('max_landsize')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('min_living_area')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('max_living_area')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('bedrooms')
                    ->searchable(),
                TextColumn::make('bathrooms')
                    ->searchable(),
                TextColumn::make('min_bedrooms')
                    ->searchable(),
                TextColumn::make('max_bedrooms')
                    ->searchable(),
                TextColumn::make('min_bathrooms')
                    ->searchable(),
                TextColumn::make('max_bathrooms')
                    ->searchable(),
                TextColumn::make('garage')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('min_rent')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('max_rent')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('avg_rent')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('min_rent_yield')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('max_rent_yield')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('avg_rent_yield')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('rent_to_sell_yield')
                    ->numeric()
                    ->sortable(),
                IconColumn::make('is_hot_property')
                    ->boolean(),
                TextColumn::make('min_price')
                    ->money()
                    ->sortable(),
                TextColumn::make('max_price')
                    ->money()
                    ->sortable(),
                TextColumn::make('avg_price')
                    ->money()
                    ->sortable(),
                TextColumn::make('body_corporate_fees')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('min_body_corporate_fees')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('max_body_corporate_fees')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('rates_fees')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('min_rates_fees')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('max_rates_fees')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('sub_agent_comms')
                    ->numeric()
                    ->sortable(),
                IconColumn::make('is_archived')
                    ->boolean(),
                IconColumn::make('is_hidden')
                    ->boolean(),
                TextColumn::make('start_at')
                    ->date()
                    ->sortable(),
                TextColumn::make('end_at')
                    ->date()
                    ->sortable(),
                IconColumn::make('is_smsf')
                    ->boolean(),
                IconColumn::make('is_firb')
                    ->boolean(),
                IconColumn::make('is_ndis')
                    ->boolean(),
                IconColumn::make('is_cashflow_positive')
                    ->boolean(),
                TextColumn::make('build_time')
                    ->searchable(),
                TextColumn::make('historical_growth')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('land_info')
                    ->searchable(),
                TextColumn::make('developer.id')
                    ->searchable(),
                TextColumn::make('projecttype.title')
                    ->searchable(),
                IconColumn::make('is_featured')
                    ->boolean(),
                IconColumn::make('is_co_living')
                    ->boolean(),
                IconColumn::make('is_rooming')
                    ->boolean(),
                IconColumn::make('is_rent_to_sell')
                    ->boolean(),
                IconColumn::make('is_flexi')
                    ->boolean(),
                IconColumn::make('is_exclusive')
                    ->boolean(),
                TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('created_by')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('updated_by')
                    ->numeric()
                    ->sortable(),
            ])
            ->filters([
                //
            ])
            ->recordActions([
                ViewAction::make(),
                EditAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }
}
