<?php

namespace App\Filament\Resources\Lots\Schemas;

use App\Models\Lot;
use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class LotInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('legacy_lot_id')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('project.title')
                    ->label('Project'),
                TextEntry::make('title')
                    ->placeholder('-'),
                TextEntry::make('land_price')
                    ->money()
                    ->placeholder('-'),
                TextEntry::make('build_price')
                    ->money()
                    ->placeholder('-'),
                TextEntry::make('stage')
                    ->placeholder('-'),
                TextEntry::make('level')
                    ->placeholder('-'),
                TextEntry::make('building')
                    ->placeholder('-'),
                TextEntry::make('floorplan')
                    ->placeholder('-'),
                TextEntry::make('car')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('storage')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('view')
                    ->placeholder('-'),
                TextEntry::make('garage')
                    ->placeholder('-'),
                TextEntry::make('aspect')
                    ->placeholder('-'),
                TextEntry::make('internal')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('external')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('total')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('storyes')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('land_size')
                    ->placeholder('-'),
                TextEntry::make('title_status')
                    ->placeholder('-'),
                TextEntry::make('living_area')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('price')
                    ->money()
                    ->placeholder('-'),
                TextEntry::make('bedrooms')
                    ->placeholder('-'),
                TextEntry::make('bathrooms')
                    ->placeholder('-'),
                TextEntry::make('study')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('mpr')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('powder_room')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('balcony')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('rent_yield')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('weekly_rent')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('rent_to_sell_yield')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('rates')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('five_percent_share_price')
                    ->money()
                    ->placeholder('-'),
                TextEntry::make('sub_agent_comms')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('body_corporation')
                    ->numeric()
                    ->placeholder('-'),
                IconEntry::make('is_archived')
                    ->boolean(),
                IconEntry::make('is_nras')
                    ->boolean(),
                IconEntry::make('is_smsf')
                    ->boolean(),
                IconEntry::make('is_cashflow_positive')
                    ->boolean(),
                TextEntry::make('completion')
                    ->placeholder('-'),
                TextEntry::make('uuid')
                    ->label('UUID')
                    ->placeholder('-'),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('deleted_at')
                    ->dateTime()
                    ->visible(fn (Lot $record): bool => $record->trashed()),
                TextEntry::make('created_by')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('updated_by')
                    ->numeric()
                    ->placeholder('-'),
            ]);
    }
}
