<?php

declare(strict_types=1);

namespace Database\Seeders\Development;

use Illuminate\Database\Seeder;

/**
 * BillingMetric seeder.
 *
 * Billing metrics are typically generated by the GenerateBillingMetrics job.
 * This seeder exists to satisfy the model-audit / pre-commit check.
 */
final class BillingMetricSeeder extends Seeder
{
    public function run(): void
    {
        // No-op: metrics are generated by GenerateBillingMetrics job.
    }
}
