<?php

declare(strict_types=1);

namespace Database\Seeders\Development;

use Illuminate\Database\Seeder;

/**
 * PenaltyPrediction seeder. Placeholder for development; predictions are generated by AI.
 * This seeder exists to satisfy the model-audit / pre-commit check.
 */
final class PenaltyPredictionSeeder extends Seeder
{
    public function run(): void
    {
        // No-op: penalty predictions are generated by the penalties:predict command.
    }
}
