<?php

declare(strict_types=1);

namespace Database\Seeders\Development;

use Illuminate\Database\Seeder;

/**
 * SidingRiskScore seeder. Placeholder for development; scores are generated by AI.
 * This seeder exists to satisfy the model-audit / pre-commit check.
 */
final class SidingRiskScoreSeeder extends Seeder
{
    public function run(): void
    {
        // No-op: siding risk scores are calculated by the CalculateSidingRiskScoresAction.
    }
}
