<?php

namespace App\Filament\Resources\Projects\Schemas;

use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class ProjectInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('legacy_project_id')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('organization.name')
                    ->label('Organization')
                    ->placeholder('-'),
                TextEntry::make('title'),
                TextEntry::make('stage')
                    ->placeholder('-'),
                TextEntry::make('estate'),
                TextEntry::make('total_lots')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('storeys')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('min_landsize')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('max_landsize')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('min_living_area')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('max_living_area')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('bedrooms')
                    ->placeholder('-'),
                TextEntry::make('bathrooms')
                    ->placeholder('-'),
                TextEntry::make('min_bedrooms')
                    ->placeholder('-'),
                TextEntry::make('max_bedrooms')
                    ->placeholder('-'),
                TextEntry::make('min_bathrooms')
                    ->placeholder('-'),
                TextEntry::make('max_bathrooms')
                    ->placeholder('-'),
                TextEntry::make('garage')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('min_rent')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('max_rent')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('avg_rent')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('min_rent_yield')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('max_rent_yield')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('avg_rent_yield')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('rent_to_sell_yield')
                    ->numeric()
                    ->placeholder('-'),
                IconEntry::make('is_hot_property')
                    ->boolean(),
                TextEntry::make('description')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('min_price')
                    ->money()
                    ->placeholder('-'),
                TextEntry::make('max_price')
                    ->money()
                    ->placeholder('-'),
                TextEntry::make('avg_price')
                    ->money()
                    ->placeholder('-'),
                TextEntry::make('body_corporate_fees')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('min_body_corporate_fees')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('max_body_corporate_fees')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('rates_fees')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('min_rates_fees')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('max_rates_fees')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('sub_agent_comms')
                    ->numeric()
                    ->placeholder('-'),
                IconEntry::make('is_archived')
                    ->boolean(),
                IconEntry::make('is_hidden')
                    ->boolean(),
                TextEntry::make('start_at')
                    ->date()
                    ->placeholder('-'),
                TextEntry::make('end_at')
                    ->date()
                    ->placeholder('-'),
                IconEntry::make('is_smsf')
                    ->boolean(),
                IconEntry::make('is_firb')
                    ->boolean(),
                IconEntry::make('is_ndis')
                    ->boolean(),
                IconEntry::make('is_cashflow_positive')
                    ->boolean(),
                TextEntry::make('build_time')
                    ->placeholder('-'),
                TextEntry::make('historical_growth')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('land_info')
                    ->placeholder('-'),
                TextEntry::make('developer.id')
                    ->label('Developer')
                    ->placeholder('-'),
                TextEntry::make('projecttype.title')
                    ->label('Projecttype')
                    ->placeholder('-'),
                IconEntry::make('is_featured')
                    ->boolean(),
                TextEntry::make('property_conditions')
                    ->placeholder('-')
                    ->columnSpanFull(),
                IconEntry::make('is_co_living')
                    ->boolean(),
                IconEntry::make('is_rooming')
                    ->boolean(),
                IconEntry::make('is_rent_to_sell')
                    ->boolean(),
                IconEntry::make('is_flexi')
                    ->boolean(),
                IconEntry::make('is_exclusive')
                    ->boolean(),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('created_by')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('updated_by')
                    ->numeric()
                    ->placeholder('-'),
            ]);
    }
}
