<?php

declare(strict_types=1);

namespace App\Filament\Resources\Projects\Schemas;

use App\Models\Project;
use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

final class ProjectInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('organization.name')
                    ->label('Organization')
                    ->placeholder('-'),
                TextEntry::make('legacy_id')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('slug')
                    ->placeholder('-'),
                TextEntry::make('title'),
                TextEntry::make('stage'),
                TextEntry::make('estate')
                    ->placeholder('-'),
                TextEntry::make('total_lots')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('storeys')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('min_landsize')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('max_landsize')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('living_area')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('bedrooms')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('bathrooms')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('garage')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('min_rent')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('max_rent')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('avg_rent')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('rent_yield')
                    ->numeric()
                    ->placeholder('-'),
                IconEntry::make('is_hot_property')
                    ->boolean(),
                TextEntry::make('description')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('description_summary')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('min_price')
                    ->money()
                    ->placeholder('-'),
                TextEntry::make('max_price')
                    ->money()
                    ->placeholder('-'),
                TextEntry::make('avg_price')
                    ->money()
                    ->placeholder('-'),
                TextEntry::make('body_corporate_fees')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('rates_fees')
                    ->numeric()
                    ->placeholder('-'),
                IconEntry::make('is_archived')
                    ->boolean(),
                IconEntry::make('is_hidden')
                    ->boolean(),
                TextEntry::make('start_at')
                    ->date()
                    ->placeholder('-'),
                TextEntry::make('end_at')
                    ->date()
                    ->placeholder('-'),
                IconEntry::make('is_smsf')
                    ->boolean(),
                IconEntry::make('is_firb')
                    ->boolean(),
                IconEntry::make('is_ndis')
                    ->boolean(),
                IconEntry::make('is_cashflow_positive')
                    ->boolean(),
                TextEntry::make('build_time')
                    ->placeholder('-'),
                TextEntry::make('historical_growth')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('land_info')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('developer.name')
                    ->label('Developer')
                    ->placeholder('-'),
                TextEntry::make('projecttype.name')
                    ->label('Projecttype')
                    ->placeholder('-'),
                TextEntry::make('lat')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('lng')
                    ->numeric()
                    ->placeholder('-'),
                IconEntry::make('is_featured')
                    ->boolean(),
                TextEntry::make('featured_order')
                    ->numeric()
                    ->placeholder('-'),
                IconEntry::make('is_co_living')
                    ->boolean(),
                IconEntry::make('is_high_cap_growth')
                    ->boolean(),
                IconEntry::make('is_rooming')
                    ->boolean(),
                IconEntry::make('is_rent_to_sell')
                    ->boolean(),
                IconEntry::make('is_exclusive')
                    ->boolean(),
                TextEntry::make('suburb')
                    ->placeholder('-'),
                TextEntry::make('state')
                    ->placeholder('-'),
                TextEntry::make('postcode')
                    ->placeholder('-'),
                TextEntry::make('created_by')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('updated_by')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('deleted_at')
                    ->dateTime()
                    ->visible(fn (Project $record): bool => $record->trashed()),
            ]);
    }
}
